// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: error_message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from error_message.proto</summary>
public static partial class ErrorMessageReflection {

  #region Descriptor
  /// <summary>File descriptor for error_message.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ErrorMessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNlcnJvcl9tZXNzYWdlLnByb3RvKkQKB0VNX1R5cGUSEgoORU1fVU5TUEVD",
          "SUZJRUQQABITCg9FTV9ESVNDT05ORUNURUQQARIQCgxFTV9FTkRPRkZJTEUQ",
          "AmIIZWRpdGlvbnNw6Ac="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EM_Type), }, null, null));
  }
  #endregion

}
#region Enums
public enum EM_Type {
  [pbr::OriginalName("EM_UNSPECIFIED")] EmUnspecified = 0,
  [pbr::OriginalName("EM_DISCONNECTED")] EmDisconnected = 1,
  [pbr::OriginalName("EM_ENDOFFILE")] EmEndoffile = 2,
}

#endregion


#endregion Designer generated code
