// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game_message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from game_message.proto</summary>
public static partial class GameMessageReflection {

  #region Descriptor
  /// <summary>File descriptor for game_message.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GameMessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJnYW1lX21lc3NhZ2UucHJvdG8qPAoQR2FtZU1lc3NhZ2VfVHlwZRISCg5H",
          "TV9VTlNQRUNJRklFRBAAEhQKD0dNX0RJU0NPTk5FQ1RFRBCsAmIIZWRpdGlv",
          "bnNw6Ac="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameMessage_Type), }, null, null));
  }
  #endregion

}
#region Enums
public enum GameMessage_Type {
  [pbr::OriginalName("GM_UNSPECIFIED")] GmUnspecified = 0,
  [pbr::OriginalName("GM_DISCONNECTED")] GmDisconnected = 300,
}

#endregion


#endregion Designer generated code
